### ISSUE TITLE
[함수형 프로그래밍과 JavaScript ES6+ 강의] 지연된 함수열을 병렬적으로 평가하기 - C.reduce, C.take [2] 관련 질문

### ISSUE THREAD

**Issue by chichchic** [indongyoo/functional-javascript-01#2]
[10. 비동기 동시성 프로그래밍 2/1/html/1-2.html](https://github.com/indongyoo/functional-javascript-01/blob/master/10.%20%EB%B9%84%EB%8F%99%EA%B8%B0%20%EB%8F%99%EC%8B%9C%EC%84%B1%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%202/1/html/1-2.html)에서 

```javascript
const catchNoop = ([...arr]) =>
    (arr.forEach(a => a instanceof Promise ? a.catch(noop) : a), arr);
```
에서 catchNoop 함수가 리턴해주는 값의 문이 이해가 잘 가지 않네요 ㅠ
```javascript
const catchNoop = ([...arr]) =>
    {
        arr.forEach(a => a instanceof Promise ? a.catch(noop) : a)
        return arr
    };
```
로 수정하면 잘 동작하는것 같은데 제가 잘 이해하지 못한 부분이 있는걸까요 아니면 코드가 잘못된걸까요?

**Comment by indongyoo** [comment]
(1, 2); // 2
(2, 0); // 0

위 예제를 참고해주세요 :)

**Comment by chichchic** [comment]
답변 감사합니다. 소괄호로 묶어서 반환하는 문법이 있었군요.
해당 문법을 처음봐서 좀 더 찾아보고싶은데 어떤식으로 검색해야 찾아볼 수 있을까요?

**Comment by indongyoo** [comment]
감사합니다 👍
